# Site settings
title: addamhardy.com
email: addam.hardy@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http:/addamhardy.com" # the base hostname & protocol for your site
twitter_username: addamh
github_username:  addamh

# Build settings
markdown: kramdown
